export const FETCH_USERS_SEARCH_REQUEST = "FETCH_USERS_BY_SEARCH_REQUEST";
export const FETCH_USERS_SEARCH_SUCCESS = "FETCH_USERS_BY_SEARCH_SUCCESS";
export const FETCH_USERS_SEARCH_FAILED = "FETCH_USERS_SEARCH_FAILED";