export const FETCH_USERS_BY_USERNAME_REQUEST = "FETCH_USERS_BY_USERNAME_REQUEST";
export const FETCH_USERS_BY_USERNAME_SUCCESS = "FETCH_USERS_BY_USERNAME_SUCCESS";
export const FETCH_USERS_BY_USERNAME_FAILED = "FETCH_USERS_BY_USERNAME_FAILED";