export const FETCH_USERS_BY_USERNAME_REQUEST = "SEARCH_USERS_REQUEST";
export const FETCH_USERS_BY_USERNAME_SUCCESS = "SEARCH_USERS_SUCCESS";
export const FETCH_USERS_BY_USERNAME_FAILED = "SEARCH_USERS_FAILED";
export const FETCH_USERS_BY_SEARCH = "FETCH_USERS_BY_SEARCH";